// pSEO data for programmatic content generation
import { TimeGoal, RaceData } from "./types";
import marathonData from "@/data/marathon-data.json";

// Convert marathon data to RaceData format
export const races: RaceData[] = Object.entries(marathonData).map(
  ([key, data]) => ({
    key,
    name: data.name,
    city: data.city,
    country: data.country,
    distance: data.distance,
    elevationGain: data.elevationGain,
    elevationLoss: data.elevationLoss,
    raceDate: data.raceDate,
    description: data.description,
    tips: data.tips,
    paceStrategy: data.paceStrategy,
    fuelingNotes: data.fuelingNotes,
    faq: data.faq,
  })
);

// Time goal targets for each distance
// Format: targetTime, targetTimeMinutes, pacePerKm, pacePerMile, vdot, difficulty
export const timeGoals: TimeGoal[] = [
  // Marathon goals
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "5:00",
    targetTimeMinutes: 300,
    pacePerKm: "7:06",
    pacePerMile: "11:27",
    vdot: 30,
    difficulty: "beginner",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "4:30",
    targetTimeMinutes: 270,
    pacePerKm: "6:24",
    pacePerMile: "10:18",
    vdot: 34,
    difficulty: "beginner",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "4:00",
    targetTimeMinutes: 240,
    pacePerKm: "5:41",
    pacePerMile: "9:09",
    vdot: 40,
    difficulty: "intermediate",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "3:45",
    targetTimeMinutes: 225,
    pacePerKm: "5:19",
    pacePerMile: "8:34",
    vdot: 44,
    difficulty: "intermediate",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "3:30",
    targetTimeMinutes: 210,
    pacePerKm: "4:58",
    pacePerMile: "8:00",
    vdot: 48,
    difficulty: "advanced",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "3:15",
    targetTimeMinutes: 195,
    pacePerKm: "4:37",
    pacePerMile: "7:26",
    vdot: 52,
    difficulty: "advanced",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "3:00",
    targetTimeMinutes: 180,
    pacePerKm: "4:16",
    pacePerMile: "6:52",
    vdot: 57,
    difficulty: "elite",
  },
  {
    distance: "marathon",
    distanceLabel: "Marathon",
    distanceKm: 42.195,
    targetTime: "2:45",
    targetTimeMinutes: 165,
    pacePerKm: "3:55",
    pacePerMile: "6:17",
    vdot: 63,
    difficulty: "elite",
  },

  // Half Marathon goals
  {
    distance: "half-marathon",
    distanceLabel: "Half Marathon",
    distanceKm: 21.0975,
    targetTime: "2:30",
    targetTimeMinutes: 150,
    pacePerKm: "7:06",
    pacePerMile: "11:27",
    vdot: 30,
    difficulty: "beginner",
  },
  {
    distance: "half-marathon",
    distanceLabel: "Half Marathon",
    distanceKm: 21.0975,
    targetTime: "2:15",
    targetTimeMinutes: 135,
    pacePerKm: "6:24",
    pacePerMile: "10:18",
    vdot: 34,
    difficulty: "beginner",
  },
  {
    distance: "half-marathon",
    distanceLabel: "Half Marathon",
    distanceKm: 21.0975,
    targetTime: "2:00",
    targetTimeMinutes: 120,
    pacePerKm: "5:41",
    pacePerMile: "9:09",
    vdot: 40,
    difficulty: "intermediate",
  },
  {
    distance: "half-marathon",
    distanceLabel: "Half Marathon",
    distanceKm: 21.0975,
    targetTime: "1:45",
    targetTimeMinutes: 105,
    pacePerKm: "4:58",
    pacePerMile: "8:00",
    vdot: 48,
    difficulty: "intermediate",
  },
  {
    distance: "half-marathon",
    distanceLabel: "Half Marathon",
    distanceKm: 21.0975,
    targetTime: "1:30",
    targetTimeMinutes: 90,
    pacePerKm: "4:16",
    pacePerMile: "6:52",
    vdot: 57,
    difficulty: "advanced",
  },
  {
    distance: "half-marathon",
    distanceLabel: "Half Marathon",
    distanceKm: 21.0975,
    targetTime: "1:20",
    targetTimeMinutes: 80,
    pacePerKm: "3:47",
    pacePerMile: "6:06",
    vdot: 65,
    difficulty: "elite",
  },

  // 10K goals
  {
    distance: "10k",
    distanceLabel: "10K",
    distanceKm: 10,
    targetTime: "60:00",
    targetTimeMinutes: 60,
    pacePerKm: "6:00",
    pacePerMile: "9:39",
    vdot: 35,
    difficulty: "beginner",
  },
  {
    distance: "10k",
    distanceLabel: "10K",
    distanceKm: 10,
    targetTime: "55:00",
    targetTimeMinutes: 55,
    pacePerKm: "5:30",
    pacePerMile: "8:51",
    vdot: 39,
    difficulty: "beginner",
  },
  {
    distance: "10k",
    distanceLabel: "10K",
    distanceKm: 10,
    targetTime: "50:00",
    targetTimeMinutes: 50,
    pacePerKm: "5:00",
    pacePerMile: "8:03",
    vdot: 44,
    difficulty: "intermediate",
  },
  {
    distance: "10k",
    distanceLabel: "10K",
    distanceKm: 10,
    targetTime: "45:00",
    targetTimeMinutes: 45,
    pacePerKm: "4:30",
    pacePerMile: "7:14",
    vdot: 50,
    difficulty: "intermediate",
  },
  {
    distance: "10k",
    distanceLabel: "10K",
    distanceKm: 10,
    targetTime: "40:00",
    targetTimeMinutes: 40,
    pacePerKm: "4:00",
    pacePerMile: "6:26",
    vdot: 58,
    difficulty: "advanced",
  },
  {
    distance: "10k",
    distanceLabel: "10K",
    distanceKm: 10,
    targetTime: "35:00",
    targetTimeMinutes: 35,
    pacePerKm: "3:30",
    pacePerMile: "5:38",
    vdot: 68,
    difficulty: "elite",
  },

  // 5K goals
  {
    distance: "5k",
    distanceLabel: "5K",
    distanceKm: 5,
    targetTime: "30:00",
    targetTimeMinutes: 30,
    pacePerKm: "6:00",
    pacePerMile: "9:39",
    vdot: 33,
    difficulty: "beginner",
  },
  {
    distance: "5k",
    distanceLabel: "5K",
    distanceKm: 5,
    targetTime: "25:00",
    targetTimeMinutes: 25,
    pacePerKm: "5:00",
    pacePerMile: "8:03",
    vdot: 42,
    difficulty: "intermediate",
  },
  {
    distance: "5k",
    distanceLabel: "5K",
    distanceKm: 5,
    targetTime: "22:00",
    targetTimeMinutes: 22,
    pacePerKm: "4:24",
    pacePerMile: "7:05",
    vdot: 50,
    difficulty: "intermediate",
  },
  {
    distance: "5k",
    distanceLabel: "5K",
    distanceKm: 5,
    targetTime: "20:00",
    targetTimeMinutes: 20,
    pacePerKm: "4:00",
    pacePerMile: "6:26",
    vdot: 56,
    difficulty: "advanced",
  },
  {
    distance: "5k",
    distanceLabel: "5K",
    distanceKm: 5,
    targetTime: "18:00",
    targetTimeMinutes: 18,
    pacePerKm: "3:36",
    pacePerMile: "5:48",
    vdot: 64,
    difficulty: "elite",
  },
  {
    distance: "5k",
    distanceLabel: "5K",
    distanceKm: 5,
    targetTime: "16:00",
    targetTimeMinutes: 16,
    pacePerKm: "3:12",
    pacePerMile: "5:09",
    vdot: 74,
    difficulty: "elite",
  },
];
